version: '3.7'

services:
  db:
    image: postgres:13.7-alpine
    ports:
      - 15432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  backend:
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - ./app:/app
    build:
      context: ./app
    ports:
      - 8000:8000
    depends_on:
      - db
      - memcached

  rabbitmq:
    image: rabbitmq:3.9.27-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/data

  memcached:
    image: bitnami/memcached:1.6.21

  celery:
    command: ['celery', '-A', 'app', 'worker', '-l', 'INFO']
    build:
      context: ./app
    restart: unless-stopped
    volumes:
      - ./app:/app
    depends_on:
      - rabbitmq
      - memcached
      - backend

volumes:
  rabbitmq_data: