# Generated by Django 4.2 on 2023-06-23 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Фамилия')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Название')),
                ('attitude', models.CharField(blank=True, choices=[('negative', 'Отрицательное'), ('positive', 'Положительное')], max_length=20, null=True, verbose_name='Отношение')),
                ('importance', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Важность')),
                ('participant', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='participant.participant')),
            ],
        ),
    ]
